In [1]:
!pip install numpy

In [6]:
import numpy as np

data = np.random.rand(1,2,3,4,5)

print(data)


[[[[[0.97161487 0.67292111 0.46615563 0.18656741 0.91555872]
    [0.73740168 0.01886673 0.58207214 0.15321249 0.50428791]
    [0.28688893 0.45436011 0.70423064 0.51922742 0.25492647]
    [0.01520643 0.48236356 0.87305834 0.59700935 0.72706811]]

   [[0.5594272  0.20870312 0.8311904  0.26090344 0.82928437]
    [0.14815235 0.12082936 0.26439982 0.69098116 0.17222351]
    [0.57622223 0.84145384 0.48540674 0.37784448 0.73882085]
    [0.68505709 0.42026616 0.36774017 0.56973111 0.14970315]]

   [[0.40458731 0.57006002 0.52023066 0.32761306 0.88793635]
    [0.81099429 0.21031515 0.52118512 0.21258851 0.53196574]
    [0.31882521 0.08013101 0.7503847  0.03105719 0.3509277 ]
    [0.87987048 0.86593781 0.83090513 0.87893233 0.63269277]]]


  [[[0.01169417 0.08581151 0.81365877 0.36998263 0.5882621 ]
    [0.66077472 0.87749007 0.17270977 0.42553315 0.73111289]
    [0.39083403 0.4329388  0.68210886 0.47543524 0.22333169]
    [0.63816991 0.84172903 0.01682949 0.46956257 0.12095661]]

   [[0.5052610

In [7]:
data.size

120